### ISSUE TITLE
Add  "useLegacyAOT no" support to master branch

### ISSUE THREAD

**Issue by pkubasiak** [MindScriptAct/mvcExpress-framework#90]
Hi, could you tell if you are going to add AOT no compile support to the v2 version?

Thx for good work. Great job.

**Comment by MindScriptAct** [comment]
Hi, its in my plans.
 will have time for it next weak.

**Comment by pkubasiak** [comment]
what is the status of this issue? because Air 16 released and now this framework is completely non-functional.

**Comment by MindScriptAct** [comment]
wip, have to borrow device to test it properly.

**Comment by MindScriptAct** [comment]
fixed in theory on the branch... could not test it on device.
 will merge it as soon as I do that.

**Comment by MindScriptAct** [comment]
oh... it looks like this commits breaks some test... fixing.

**Comment by MindScriptAct** [comment]
fixed..

**Comment by pkubasiak** [comment]
Thx i will test it and let you know if it is ok.

**Comment by pkubasiak** [comment]
I tested the changes and everything works. Tested on Air 16 and Iphone. Great thanks for the good work Raimundas.

**Comment by MindScriptAct** [comment]
Awesome! Sorry it took it so long.

**Comment by MindScriptAct** [comment]
Merged into master.
